print ("Введите количество первого товара:")
wght1 = float(input())
print ("Введите цену за единицу первого товара:")
price1 = int(input())
print ("Введите количество второго товара:")
wght2 = float(input())
print ("Введите цену за единицу второго товара:")
price2 = int(input())
print ("Введите количество третьего товара:")
wght3 = float(input())
print ("Введите цену за единицу третьего товара:")
price3 = int(input())
print ("Введите количество средств покупателя:")
cash = int(input())
chng = cash - (wght1 * price1 + wght2 * price2 + wght3 * price3)
print ("Сдача равна:", int(chng))